# -*- coding: utf-8 -*-
"""cybersecurity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTh0yzEALCkfRKde-bfAB9Hed0Pc8-S9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = "Global_Cybersecurity_Threats_2015-2024.csv"
df = pd.read_csv(file_path)

df.head()

print(f"Dataset contains {df.shape[0]} rows and {df.shape[1]} columns.")

df.info()

df.describe(include='all')

missing = df.isnull().sum()
print("Missing values per column:\n", missing)

df.drop_duplicates(inplace=True)

text_columns = [
    'Country', 'Attack Type', 'Target Industry',
    'Attack Source', 'Security Vulnerability Type',
    'Defense Mechanism Used'
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.title()

df['Year'] = df['Year'].astype(int)
df['Financial Loss (in Million $)'] = df['Financial Loss (in Million $)'].astype(float)
df['Number of Affected Users'] = df['Number of Affected Users'].astype(int)
df['Incident Resolution Time (in Hours)'] = df['Incident Resolution Time (in Hours)'].astype(int)

Q1 = df['Financial Loss (in Million $)'].quantile(0.25)
Q3 = df['Financial Loss (in Million $)'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Keep only rows within the normal range
df = df[(df['Financial Loss (in Million $)'] >= lower_bound) & (df['Financial Loss (in Million $)'] <= upper_bound)]

df.to_excel("Cleaned_Global_Cybersecurity_Threats.xlsx", index=False)

from google.colab import files
files.download("Cleaned_Global_Cybersecurity_Threats.xlsx")